name: Useless100
main: com.lotest.useless100.Useless100Plugin
version: 1.0.0
api-version: 1.12
authors: [LoTest]
description: A Paper plugin that contains 100 completely useless features.
commands:
  useless:
    description: Show or use one of the 100 useless features.
    usage: /useless [list|1-100]
    aliases: [u100]
